export const navigationItems = [
  {
    key: 'dashboard',
    label: 'Home',
    routeName: 'dashboard',
    shortDescription: 'Operational overview, order flow, and workspace health',
    requiredPlan: 'FREE',
    icon: 'home',
    category: 'workspace',
  },
  {
    key: 'inventory',
    label: 'Inventory',
    routeName: 'inventory',
    shortDescription: 'Stock ledger, warehouses, transfers, and low-stock visibility',
    requiredPlan: 'FREE',
    icon: 'layers',
    category: 'workspace',
  },
  {
    key: 'sales',
    label: 'Sales',
    routeName: 'sales',
    shortDescription: 'Orders, sell-through movement, and sales intelligence',
    requiredPlan: 'PREMIUM',
    icon: 'chart',
    category: 'workspace',
  },
  {
    key: 'purchasing',
    label: 'Purchasing',
    routeName: 'purchasing',
    shortDescription: 'Supplier orders, receiving, reorder planning, and inbound control',
    requiredPlan: 'PREMIUM',
    icon: 'cart',
    category: 'workspace',
  },
  {
    key: 'returns',
    label: 'Returns',
    routeName: 'returns',
    shortDescription: 'Refunds, leakage analysis, and reverse logistics context',
    requiredPlan: 'PREMIUM',
    icon: 'rotate',
    category: 'workspace',
  },
  {
    key: 'logistics',
    label: 'Logistics',
    routeName: 'logistics',
    shortDescription: 'Port pressure, route flow, and shipment delay intelligence',
    requiredPlan: 'BOOST',
    icon: 'ship',
    category: 'operations',
  },
  {
    key: 'compliance',
    label: 'MCP + RAG',
    routeName: 'compliance',
    shortDescription: 'AI tools, compliance retrieval, and structured recommendations',
    requiredPlan: 'PREMIUM',
    icon: 'spark',
    category: 'operations',
  },
  {
    key: 'einvoicing',
    label: 'E-Invoicing',
    routeName: 'compliance',
    shortDescription: 'LHDN-ready transaction workflows and compliance readiness',
    requiredPlan: 'PREMIUM',
    icon: 'receipt',
    category: 'operations',
  },
  {
    key: 'plans',
    label: 'Plans',
    routeName: 'plans',
    shortDescription: 'Free, Premium, and Boost workspace capabilities',
    requiredPlan: 'FREE',
    icon: 'crown',
    category: 'commercial',
  },
  {
    key: 'copilot',
    label: 'AI Copilot',
    routeName: 'copilot',
    shortDescription: 'MCP-backed assistant for inventory, logistics, and compliance',
    requiredPlan: 'FREE',
    icon: 'bot',
    category: 'operations',
  },
  {
    key: 'notifications',
    label: 'Notifications',
    routeName: 'alerts',
    shortDescription: 'Unread alerts, notification preferences, and operational exceptions',
    requiredPlan: 'FREE',
    icon: 'bell',
    category: 'operations',
  },
  {
    key: 'account',
    label: 'Profile',
    routeName: 'account',
    shortDescription: 'Workspace identity, account details, and plan context',
    requiredPlan: 'FREE',
    icon: 'user',
    category: 'account',
  },
];

export const trackerOrder = navigationItems.map((item) => item.key);

export function getNavigationItemByRoute(routeName) {
  return navigationItems.find((item) => item.routeName === routeName || item.key === routeName) || navigationItems[0];
}
